name: Go

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build dm0610/gb-go-level-1

    - name: Test
      run: chmod +x ./gb-go-level-1 && ./gb-go-level-1
